Repository team-mozu/mozu-BE, pull requests merged in 2025-02, with the labels that each got.

#16 feat :: 기관 API 개발
  package.json
  src/app.module.ts
  src/article/domain/persistence/article.entity.ts
  src/class/domain/class/persistence/class.entity.ts
  src/common/data/Role.ts
  src/common/decorator/authority.decorator.ts
  src/common/decorator/user.decorator.ts
  src/common/guard/jwt.guard.ts
  src/infrastructure/database.config.ts
  src/organ/application/impl/.gitkit
  src/organ/application/impl/organ.read.service.impl.ts
  src/organ/application/impl/organ.write.service.impl.ts
  src/organ/application/organ.application.module.ts
  src/organ/application/organ.read.service.ts
  src/organ/application/organ.write.service.ts
  src/organ/common/.gitkit
  src/organ/common/data/organ.dto.ts
  src/organ/domain/.gitkit
  src/organ/domain/organ.domain.module.ts
  src/organ/domain/organ.domain.reader.ts
  src/organ/domain/organ.domain.writer.ts
  src/organ/domain/persistence/.gitkit
  src/organ/domain/persistence/organ.domain.mapper.ts
  src/organ/domain/persistence/organ.entity.ts
  src/organ/domain/persistence/organ.repository.ts
  src/organ/organ.module.ts
  src/organ/presentation/.gitkit
  src/organ/presentation/form/.gitkit
  src/organ/presentation/form/request/.gitkit
  src/organ/presentation/form/request/request.login.form.ts
  src/organ/presentation/form/request/request.organ.form.mapper.ts
  src/organ/presentation/form/request/request.organ.form.ts
  src/organ/presentation/form/response/.gitkit
  src/organ/presentation/form/response/response.login.form.ts
  src/organ/presentation/organ.presentation.module.ts
  src/organ/presentation/organ.read.adapter.ts
  src/organ/presentation/organ.write.adapter.ts
  yarn.lock
Labels: 🧑‍💻 feat

#18 feat :: 종목 API 개발
  src/app.module.ts
  src/infrastructure/database.config.ts
  src/item/application/impl/.gitkit
  src/item/application/impl/item.read.service.impl.ts
  src/item/application/impl/item.write.service.impl.ts
  src/item/application/item.application.module.ts
  src/item/application/item.read.service.ts
  src/item/application/item.write.service.ts
  src/item/common/.gitkit
  src/item/common/data/item.dto.ts
  src/item/domain/.gitkit
  src/item/domain/item.domain.module.ts
  src/item/domain/item.domain.reader.ts
  src/item/domain/item.domain.writer.ts
  src/item/domain/persistence/.gitkit
  src/item/domain/persistence/item.domain.mapper.ts
  src/item/domain/persistence/item.entity.ts
  src/item/domain/persistence/item.repository.ts
  src/item/item.module.ts
  src/item/presentation/.gitkit
  src/item/presentation/document/.gitkit
  src/item/presentation/form/.gitkit
  src/item/presentation/form/request/.gitkit
  src/item/presentation/form/request/request.item.form.mapper.ts
  src/item/presentation/form/request/request.item.form.ts
  src/item/presentation/form/response/.gitkit
  src/item/presentation/form/response/response.item.form.ts
  src/item/presentation/item.presentation.module.ts
  src/item/presentation/item.read.adapter.ts
  src/item/presentation/item.write.adapter.ts
  src/organ/application/impl/organ.read.service.impl.ts
  src/organ/domain/persistence/organ.entity.ts
Labels: 🧑‍💻 feat

#20 feat :: 기사 API 리팩토링
  src/article/application/article.read.service.ts
  src/article/application/article.write.service.ts
  src/article/application/impl/article.read.service.impl.ts
  src/article/application/impl/article.write.service.impl.ts
  src/article/domain/article.domain.module.ts
  src/article/domain/article.domain.reader.ts
  src/article/domain/article.domain.writer.ts
  src/article/domain/persistence/article.checker.ts
  src/article/domain/persistence/article.repository.ts
  src/article/presentation/article.presentation.module.ts
  src/article/presentation/article.read.adapter.ts
  src/article/presentation/article.write.adapter.ts
  src/article/presentation/document/article.read.documentation.ts
  src/article/presentation/document/article.write.documentation.ts
  src/article/presentation/form/request/request.article.form.ts
  src/common/filter/global.exception.filter.ts
  src/item/presentation/form/request/request.item.form.ts
  src/main.ts
  src/organ/presentation/form/request/request.login.form.ts
  src/organ/presentation/form/request/request.organ.form.ts
Labels: 🧑‍💻 feat, ♻️ refactor

#22 refactor :: 기관 API 리팩토링
  src/organ/application/impl/organ.read.service.impl.ts
  src/organ/application/organ.read.service.ts
  src/organ/domain/organ.domain.module.ts
  src/organ/domain/persistence/organ.repository.ts
  src/organ/presentation/document/.gitkit
  src/organ/presentation/form/response/response.reissue.form.ts
  src/organ/presentation/organ.read.adapter.ts
  src/organ/presentation/organ.write.adapter.ts
Labels: 🧑‍💻 feat, ♻️ refactor

#25 feat :: 보유주식 등록 조회 기능 개발
  package-lock.json
  package.json
  src/app.module.ts
  src/common/data/hold-item/hold-item.dto.ts
  src/hold-item/application/application.module.ts
  src/hold-item/application/hold-item.read.service.ts
  src/hold-item/application/hold-item.write.service.ts
  src/hold-item/application/impl/hold-item.read.service.impl.ts
  src/hold-item/application/impl/hold-item.write.service.impl.ts
  src/hold-item/domain/domain.module.ts
  src/hold-item/domain/hold-item.domain.reader.ts
  src/hold-item/domain/hold-item.domain.writer.ts
  src/hold-item/domain/persistence/hold-item.checker.ts
  src/hold-item/domain/persistence/hold-item.domain.mapper.ts
  src/hold-item/domain/persistence/hold-item.entity.ts
  src/hold-item/domain/persistence/hold-item.repository.ts
  src/hold-item/hold-item.module.ts
  src/hold-item/presentation/form/request/request.hold-item.form.ts
  src/hold-item/presentation/form/request/request.hold-item.from.mapper.ts
  src/hold-item/presentation/form/response/response.hold-item.form.ts
  src/hold-item/presentation/hold-item.read.adapter.ts
  src/hold-item/presentation/hold-item.write.adapter.ts
  src/hold-item/presentation/presentation.module.ts
  src/infrastructure/database.config.ts
  yarn.lock
Labels: 🧑‍💻 feat

#31 refactor :: 종목 수정 api 로직 변경
  src/item/domain/persistence/item.repository.ts
  src/item/presentation/form/request/request.item.form.mapper.ts
  src/item/presentation/form/request/request.item.form.ts
  src/item/presentation/item.write.adapter.ts
Labels: ♻️ refactor

#33 bug :: 기사 수정 API 버그 수정
  src/article/domain/persistence/article.repository.ts
  src/article/presentation/article.write.adapter.ts
  src/article/presentation/form/request/request.article.form.mapper.ts
  src/article/presentation/form/request/request.article.form.ts
Labels: 👾 BUG
